name: CI

on:
  push:
    branches-ignore:
      - 'l10n**'
  pull_request:
    branches-ignore:
      - 'l10n**'

jobs:

  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
        mysql: [ '5.7' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up MySQL ${{ matrix.mysql }}
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql }}
          mysql root password: 'root'
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Install
        run: |
          rm composer.lock
          composer u --no-progress
      - name: CGL
        run: |
          composer ci:php:cs
      -
        name: Lint
        run: |
          composer ci:php:lint
      -
        name: PHPStan
        run: |
          composer ci:php:stan -- --error-format=github
      -
        name: Unit Tests
        run: |
          composer ci:tests:unit
